spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/zvon73
    username: root
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

jwt:
  secret: "62A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  expiration: 3600000
server:
  port: 8080