spring:
  application.name: spring
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

token:
  signing:
    key: "TestKeyForZvon73"
jwt:
  secret: "62A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  expiration: 3600000
server:
  port: 8080